services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    
    App\Service\DigitalRandomizerInterface:
        class: App\Tests\Selective\DigitalRandomizerAlwaysOneMock
